imports:
  - php

filter:
  excluded_paths: [ build, vendor, database, tests ]

checks:
  php: true

build:
  project_setup:
    override:
      - true

  environment:
    apt_packages:
      - build-essential
    php:
      version: 8.0.9

  root_path: './backend/'

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      tests:
        override:
          - command: touch build/coverage.clover && make phpunit
            coverage:
              file: build/coverage.clover
              format: clover
