<?php

/**
 * Use strict mode.
 */
declare(strict_types=1);


/**
 * Declaration of the models namespace and use of other namespaces.
 */
namespace  App\Tests;
use App\Http\Controllers\CityController;
use PHPUnit\Framework\TestCase;


/**
 * Test cases for City Controller Class.
 */
class CityControllerTest extends TestCase
{
    protected object $cityController;


    /**
     * @description setUp for test suit. Each test case will run this at first.
     */
    final protected function setUp(): void
    {
        $this->cityController = new CityController();
    }


    /**
     * @description tearDown for test suit. Each test case will run this when done is done.
     */
    final protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    /**
     * @test
     * @description Test existence of methods for Bike Controller class.
     */
    final public function test_CityController_methods_existence(): void
    {
        /* Test existence of expected class methods */
        $this->assertTrue(method_exists($this->cityController, "getCities"), "City Controller Class does not have expected method to get all cities.");
        $this->assertTrue(method_exists($this->cityController, "getCity"), "City Controller Class does not have expected method to get specific city.");
        $this->assertTrue(method_exists($this->cityController, "addCity"), "City Controller Class does not have expected method to add new city to database.");
        $this->assertTrue(method_exists($this->cityController, "updateCity"), "City Controller Class does not have expected method to update a city.");
        $this->assertTrue(method_exists($this->cityController, "deleteCity"), "City Controller Class does not have expected method to delete bike from database.");
    }


//    /**
//     * @test
//     * @description Test existence of methods for Bike Controller class.
//     */
//    final public function test_BikeController_methods_response_code(): void
//    {
//        /* Test response from class methods */
//        $getResponse = $this->cityController->getBikes();
//        $getResponse->assertStatus(200);
//    }
}
